### ISSUE TITLE
Login Not Working

### ISSUE THREAD

**Issue by ryanmac8** [asjoyner/tesladeliverydate#1]
It looks like the login is failing to perform and no longer works. I'm not sure if Tesla made any changes on their side but it's just saying it can't find the sign out button and the page response just shows the login page again.

Are you having the same issues?

**Comment by asjoyner** [comment]
Tesla seems to have meaningfully refreshed the website since I last looked at it.  I could try to fix up the login handling, but my car has been delivered, so I don't have an account with an active reservation to test with and fix the reservation-page parsing.  I assume that my very brittle HTML element parsing will be broken by the refresh.

I'd happily accept PRs if you want to fix it, or feel free to branch it and use this as a starting point.

**Comment by asjoyner** [comment]
I poked around at the site for a bit, and it seems that they've triggering a recaptcha when my code submits the login page.  I'm not sure what the trigger is, but unfortunately that's raised the bar beyond what I'm willing to try to automate around this afternoon.

If you want to try to automate around it, you could pull the cookies from a logged-in browser session, add support for them to the config, and essentially skip the login and "reuse" the logged-in session to fetch the profileUrl page.

Best wishes!

**Comment by asjoyner** [comment]
#8eacbd8704b3ed42b5c0b41c92e6340d4c54ce0a updates the README to reflect that this is broken, and adds some debugging that might help anyone who wants to dig in to try to fix it.

Thanks for letting me know, @ryanmac8 !
